---
apiVersion: v1
kind: Service
metadata:
  name: wil-app
  namespace: dev
spec:
  selector:
    app: wil-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-app-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: wil.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wil-app
                port:
                  number: 80

